language: node_js
node_js:
  - "10"

cache:
  yarn: false

install:
  - yarn install
  - yarn bootstrap --core

script:

jobs:
  include:
    - script: travis_wait 30 yarn test --cli
      name: "CLI Fixtures" 
    - script: travis_wait 30 yarn test-latest-cra
      name: "CRA latest" 