compressionLevel: 0

enableGlobalCache: true

nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

packageExtensions:
  babel-preset-react-app@10.0.x:
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": ^7.16.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-3.1.1.cjs
