body:
  - type: markdown
    attributes:
      value: |
        "Thanks for taking the time to start a new discussion!
        
        Before you post:
        - Check if someone has already asked/answered your question in a previous discussion.
        
        When you're ready to post:
        - Add labels to your discussion (e.g. React, Vue, Vite) to make it clearer for other users."
