defaults: &defaults
  working_directory: /tmp/storybook
  docker:
    - image: circleci/node:8.9

version: 2
dependencies:
  pre:
    - yarn global add npm
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - core-dependencies-{{ checksum "yarn.lock" }}
            - docs-dependencies-{{ checksum "docs/yarn.lock" }}
      - run:
          name: "Install dependencies"
          command: |
            yarn install
      - run:
          name: "Bootstrapping"
          command: |
            yarn bootstrap --core --docs --reactnative --reactnativeapp
      - run:
          name: "Dirty checking"
          command: |
            yarn repo-dirty-check
      - save_cache:
          key: core-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - addons/**/node_modules
            - app/**/node_modules
            - example/cra-kitchen-sink/node_modules
            - example/vue-kitchen-sink/node_modules
            - lib/**/node_modules
      - save_cache:
          key: core-dist-{{ .Revision }}
          paths:
            - addons/**/dist
            - app/**/dist
            - lib/**/dist
      - save_cache:
          key: docs-dependencies-{{ checksum "docs/yarn.lock" }}
          paths:
            - docs/node_modules
      - save_cache:
          key: reactnative-dependencies-{{ .Revision }}
          paths:
            - examples/react-native-vanilla/node_modules
      - save_cache:
          key: reactnativeapp-dependencies-{{ .Revision }}
          paths:
            - examples/crna-kitchen-sink/node_modules
  example-kitchen-sinks:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - core-dependencies-{{ checksum "yarn.lock" }}
            - core-dist-{{ .Revision }}
      - run:
          name: "Build react kitchen-sink"
          command: |
            cd examples/cra-kitchen-sink
            yarn build-storybook
      - run:
          name: "Build vue kitchen-sink"
          command: |
            cd examples/vue-kitchen-sink
            yarn build-storybook
      - run:
          name: "Run react kitchen-sink"
          command: |
            cd examples/cra-kitchen-sink
            yarn storybook
          background: true
      - run:
          name: "Run vue kitchen-sink"
          command: |
            cd examples/vue-kitchen-sink
            yarn storybook
          background: true
      - run:
          name: Workaround for https://github.com/GoogleChrome/puppeteer/issues/290
          command: sh ./scripts/workaround-puppeteer-issue-290.sh
      - run:
          name: Integration Test - Kichen sinks
          command: yarn test --integration
      - store_artifacts:
          path: integration/__image_snapshots__
          destination: integration_image_snapshots
  example-react-native:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - reactnative-dependencies-{{ .Revision }}
            - reactnativeapp-dependencies-{{ .Revision }}
      - run:
          name: "Running React-Native example"
          command: |
            cd examples/react-native-vanilla
            yarn storybook --smoke-test
      - run:
          name: "Running React-Native-App example"
          command: |
            cd examples/crna-kitchen-sink
            yarn storybook --smoke-test
  docs:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - docs-dependencies-{{ checksum "docs/yarn.lock" }}
      - run:
          name: "Running docs"
          command: |
            yarn docs:build
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - core-dependencies-{{ checksum "yarn.lock" }}
            - core-dist-{{ .Revision }}
      - run:
          name: "Linting"
          command: |
            yarn lint
  unit-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - core-dependencies-{{ checksum "yarn.lock" }}
            - core-dist-{{ .Revision }}
            - reactnative-dependencies-{{ .Revision }}
      - run:
          name: "Install dependencies"
          command: |
            yarn install
      - run:
          name: "Bootstrapping"
          command: |
            yarn bootstrap --core --reactnative
      - run:
          name: "Unit testing"
          command: |
            yarn test --coverage --runInBand --core --reactnative
            yarn coverage
  deploy:
    <<: *defaults
    steps:
      - run:
          name: "Deploy"
          command: |
            echo "TODO"
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - example-kitchen-sinks:
          requires:
            - build
      - example-react-native:
          requires:
            - build
      - docs:
          requires:
            - build
      - lint:
          requires:
            - build
      - unit-test:
           requires:
             - build
