name: Publish canary release of PR
run-name: 'Canary release: PR #${{ inputs.pr }}, triggered by ${{ github.triggering_actor }}'

on:
  workflow_dispatch:
    inputs:
      pr:
        description: 'Which pull request number to create a canary release for'
        required: true
        type: number

env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1

concurrency:
  group: ${{ github.workflow }}-${{ inputs.pr }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  release-canary:
    name: Release canary version
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Fail if triggerer is not administrator
        uses: prince-chrismc/check-actor-permissions-action@v2.0.4
        with:
          permission: admin

      - name: Get pull request information
        id: info
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_INFO=$(gh pr view ${{ inputs.pr }} --repo ${{ github.repository }} --json isCrossRepository,headRefOid,headRefName,headRepository,headRepositoryOwner --jq '{isFork: .isCrossRepository, owner: .headRepositoryOwner.login, name: .headRepository.name, branch: .headRefName, sha: .headRefOid}')
          echo $PR_INFO
          # Loop through each key-value pair in PR_INFO and set as step output
          for key in $(echo "$PR_INFO" | jq -r 'keys[]'); do
              value=$(echo "$PR_INFO" | jq -r ".$key")
              echo "$key=$value" >> "$GITHUB_OUTPUT"
          done

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ steps.info.outputs.isFork == 'true' && format('{0}/{1}', steps.info.outputs.owner, steps.info.outputs.repository) || null }}
          ref: ${{ steps.info.outputs.sha }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.yarn/berry/cache
          key: yarn-v1-${{ hashFiles('scripts/yarn.lock') }}-${{ hashFiles('code/yarn.lock') }}
          restore-keys: |
            yarn-v1-${{ hashFiles('scripts/yarn.lock') }}-${{ hashFiles('code/yarn.lock') }}
            yarn-v1-${{ hashFiles('scripts/yarn.lock') }}
            yarn-v1

      - name: Install dependencies
        run: yarn task --task=install --start-from=install

      - name: Set version
        id: version
        working-directory: scripts
        run: |
          TIMESTAMP=$(date +%s)
          SHORT_SHA=$(git rev-parse --short ${{ steps.info.outputs.sha }})
          yarn release:version --release-type prerelease --pre-id pr-${{ inputs.pr }}-$SHORT_SHA-$TIMESTAMP --verbose

      - name: Publish v${{ steps.version.outputs.next-version }}
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: scripts
        run: yarn release:publish --tag pr-${{ inputs.pr }} --verbose

      # TODO: build summary table

      # TODO: change PR description instead
      - name: Create comment on PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ inputs.pr }}\
            --repo "${{github.repository }}"\
            --body "🚀 This pull request has been published as version \`${{ steps.version.outputs.next-version }}\` and with the tag \`pr-${{ inputs.pr }}\` (at commit \`${{ steps.info.outputs.sha }}\`).
          [You can see it on the npm registry here](https://npmjs.com/package/@storybook/cli/v/${{ steps.version.outputs.next-version }})".

      - name: Create failing comment on PR
        if: failure()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ inputs.pr }}\
            --repo "${{github.repository }}"\
            --body "Failed to publish canary version of this pull request at commit \`${{ steps.info.outputs.sha }}\`. See the failed workflow run at: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
