name: Generate And Push Repros

on:
  schedule:
    - cron: '2 2 */1 * *'
  workflow_dispatch:
  # To remove when the branch will be merged
  push:
    branches:
      - yann/sb-509-create-github-action

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup git user
        run: |
          git config --global user.name "Storybook Bot"
          git config --global user.email "bot@storybook.js.org"
      - name: Install dependencies
        run: node ./scripts/check-dependencies.js
      - name: Bootstrap Storybook libraries
        run: yarn bootstrap --prep
        working-directory: ./code
      - name: Generate repros
        run: yarn next-repro
        working-directory: ./code
      - name: Publish repros
        run: yarn publish-repros --remote=https://storybook-bot:${{ secrets.PAT_STORYBOOK_BOT}}@github.com/storybookjs/repro-templates-temp.git --push --force-push
        working-directory: ./code
