name: Generate and publish sandboxes

on:
  schedule:
    - cron: "2 2 */1 * *"
  workflow_dispatch:
  # To test fixes on push rather than wait for the scheduling, do the following:
  # 1. Uncomment the lines below and add your branch.
  push:
    branches:
      - jeppe/25922-ci-generation-of-sandboxes-fail-sometimes-on-prereleases
  # 2. Change the "ref" value to <your-branch-name> in the actions/checkout step below.
  # 3. Comment out the whole "generate-main" job starting at line 26
  # 3. 👉 DON'T FORGET TO UNDO STEP 2 AND 3 BEFORE YOU MERGE YOUR CHANGES!

env:
  YARN_ENABLE_IMMUTABLE_INSTALLS: "false"
  CLEANUP_SANDBOX_NODE_MODULES: "true"

defaults:
  run:
    working-directory: ./code

jobs:
  generate-next:
    name: Generate to next
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: jeppe/25922-ci-generation-of-sandboxes-fail-sometimes-on-prereleases

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Setup git user
        run: |
          git config --global user.name "storybook-bot"
          git config --global user.email "32066757+storybook-bot@users.noreply.github.com"

      - name: Install dependencies
        working-directory: ./scripts
        run: node --experimental-modules ./check-dependencies.js

      - name: Compile Storybook libraries
        run: yarn task --task compile --start-from=auto --no-link

      - name: Publish to local registry
        run: yarn local-registry --publish

      - name: Run local registry
        run: yarn local-registry --open &

      - name: Wait for registry
        run: yarn wait-on tcp:127.0.0.1:6001

      - name: Generate
        id: generate
        run: yarn generate-sandboxes --local-registry

      - name: Publish
        # publish sandboxes even if the generation fails, as some sandboxes might have been generated successfully
        if: !cancelled()
        run: yarn publish-sandboxes --remote=https://storybook-bot:${{ secrets.PAT_STORYBOOK_BOT }}@github.com/storybookjs/sandboxes.git --push --branch=next

      - name: Report failure to Discord
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_MONITORING_URL }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            The generation of some or all sandboxes on the **next** branch has failed.
            [View Job](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ github.job }})

            ${{ steps.generate.outputs.failed-before-script-templates && format('The following templates failed to execute the before script:\n- {0}', steps.generate.outputs.failed-before-script-templates) || '' }}

            ${{ steps.generate.outputs.failed-before-script-templates && format('The following templates failed to initialize Storybook:\n- {0}', steps.generate.outputs.failed-init-templates) || '' }}
