name: Export to linear

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  trigger:
    if: github.event.label.name == 'linear'
    name: Export to linear
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          echo "issue ${{ github.event.issue }}"
          echo "gh repo ${{ github.event.repository }}"
          echo "gh repo ${{ github.event.repository.name }}"
      - name: Linear action
        uses: shilman/linear-action@v1
        with:
          ghIssueNumber: ${{ github.event.issue.number }}
          ghRepoOwner: ${{ github.event.repository.owner }}
          ghRepoName: ${{ github.event.repository.name }}
          ghToken: ${{ secrets.LINEAR_GH_TOKEN }}
          linearIssuePrefix: SB
          linearLabel: Storybook
          linearPRLabel: PR
          linearTeam: CH
          linearApiKey: ${{ secrets.LINEAR_API_KEY }}
        env:
          ACTIONS_STEP_DEBUG: true
