name: Export to linear

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  trigger:
    if: github.event.label.name == 'linear'
    name: Export to linear
    runs-on: ubuntu-latest
    steps:
      - name: Export to linear
        run: >
          yarn linear-export ${{ github.event.number }}"}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
