name: CLI tests

on: 
  push:
    paths:
    - 'lib/**'
    - 'app/**'

jobs:
  cli:
    name: CLI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/checkout@v1
    - name: install, bootstrap
      run: |
        yarn bootstrap --core
    - name: cli
      run: |
        yarn test --cli
  latest-cra:
    name: Latest CRA
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/checkout@v1
    - name: install, bootstrap
      run: |
        yarn bootstrap --core
    - name: latest-cra
      run: |
        yarn test-latest-cra